### ISSUE TITLE
Unable to find RMpro on another subnet

### ISSUE THREAD

**Issue by fliptoback** [t0mer/broadlinkmanager-docker#2]
Hi, my RMpro is connected to wifi on another subnet 192.168.3.125.

My home-assistant is in a docker on a linux box on IP 192.168.1.111. I am able to ping the RMpro on 192.168.3.125 from the linux box.

Broadlink manager has been installed to a docker container on the linux box. Upon launching the web interface, the searching for devices is unable to return with RMpro. It just cannot find the device.

What should I do?

**Comment by t0mer** [comment]
Hi,
Broadlink Manager is based on python broadlink and broadlink protocol,
Broadlink is using MAC Address to communicate with the device and MAC adress cannot
be bridged between networks.

**Comment by fliptoback** [comment]
Thanks Tomer for the reply. 

In my house I have all wireless devices connecting to the 192.168.3 subnet and all wired devices to the 192.168.1 subnet.

So does it mean that no matter what I do, broadlink manager will not work with this arrangement?

Thanks again!

**Comment by RobHofmann** [comment]
I'm facing the same issue here.

**Comment by liarjo** [comment]
Same issue

**Comment by clabnet** [comment]
+1

**Comment by dfarrall** [comment]
+1, looks like a great tool but can't use it based on this.

**Comment by LucidityCrash** [comment]
find the devices.json file on your filesystem and put in the correct details  something like ...
[{"name":"RM Mini 3","type":"0x5f36","ip":"192.168.1.100","mac":"xxxxxxxxxxxx"}]

For the type look in the app (Android) and go to the Device info page look at at the PID ... mine shows 
000000000000000000000000365f0000 (24 zero's, a hex number, and then 4 zeros)
take the hex number 365f, this is little endian so the devce ID is 0x5f36 in my case.

HTH.

**Comment by fliptoback** [comment]
> find the devices.json file on your filesystem and put in the correct details something like ...
> [{"name":"RM Mini 3","type":"0x5f36","ip":"192.168.1.100","mac":"xxxxxxxxxxxx"}]
> 
> For the type look in the app (Android) and go to the Device info page look at at the PID ... mine shows
> 000000000000000000000000365f0000 (24 zero's, a hex number - well the whole thing is a hex number but you know what I mean, and then 4 zeros)
> take the hex number 365f, which translates into a devce ID of 0x5f36 in my case.
> 
> HTH.

Thanks LucidityCrash.

I would like to give it a try. I can figure out the PID via the Android app but where do I find this devices.json file?

**Comment by LucidityCrash** [comment]
To access it on the machine you run Docker on it will be in the folder you specified in the Volume option.
Assuming you used the docker compose given in the readme : 
```
version: "3.6"
services:
  broadlinkmanager:
    image: techblog/broadlinkmanager
    network_mode: host
    container_name: broadlinkmanager
    restart: always
    restart: unless-stopped
    volumes:
      - ./broadlinkmanager:/opt/broadlinkmanager/data
``` 

then it will be in the folder broadlink (which will be in whatever folder you were in when you ran docker compose.
If you just did a docker run, for example like : 
```
docker run -d --restart=unless-stopped -v /opt/docker/broadlinkmanager:/opt/broadlinkmanager/data --net=host --name broadlinkmanager techblog/broadlinkmanager
```
then it will be in /opt/docker/broadlinkmanager

**Comment by fliptoback** [comment]
> To access it on the machine you run Docker on it will be in the folder you specified in the Volume option.
> Assuming you used the docker compose given in the readme :
> 
> ```
> version: "3.6"
> services:
>   broadlinkmanager:
>     image: techblog/broadlinkmanager
>     network_mode: host
>     container_name: broadlinkmanager
>     restart: always
>     restart: unless-stopped
>     volumes:
>       - ./broadlinkmanager:/opt/broadlinkmanager/data
> ```
> 
> then it will be in the folder broadlink (which will be in whatever folder you were in when you ran docker compose.
> If you just did a docker run, for example like :
> 
> ```
> docker run -d --restart=unless-stopped -v /opt/docker/broadlinkmanager:/opt/broadlinkmanager/data --net=host --name broadlinkmanager techblog/broadlinkmanager
> ```
> 
> then it will be in /opt/docker/broadlinkmanager
> 
> btw you might already realise but just in case - the xxxxxxxxxxxx for the mac need to be set to the mac off the RM Mini which you'll find in the app too.

Thanks for your reply.

This is my docker-compose file:

```
version: "3.6"
services:
  broadlinkmanager:
    image: techblog/broadlinkmanager
    network_mode: host
    container_name: broadlinkmanager
    restart: always
    restart: unless-stopped
    volumes:
      - /volume1/docker/broadlinkmanager:/opt/broadlinkmanager/data
```
When I check the actual physical /volume1/docker/broadlinkmanager directory or when i shell into the broadlinkmanager docker container and then cd to /opt/broadmanager/data, I don't see any json devices file.

The only i see is my docker-compose.yml which I just left at /volume1/docker/broadlinkmanager folder.

I know I am missing something but I couldn't figure out what.

Broadlinkmanager is running at port 7020 and the web interface loads - but just continues to "searching for devices".

Any idea please?
