### ISSUE TITLE
No interface or no devices

### ISSUE THREAD

**Issue by zmlklfe** [t0mer/broadlinkmanager-docker#55]
Running broadlinkmanager on docker on synology. 
I can get the web-interface working by running the container, but then i cannot find any broadlink devices. 
I guess it is due to network_mode is supposed to be set to host. If i set it to host, the web interface disappears. 

Does anyone know how to solve this?

**Comment by btzs** [comment]
Can you post the output of your docker or docker-compose?

I have many other docker networks which caused problems. I solved it by setting the environment variable DISCOVERY_IP_LIST in my docker-compose.yml:

```
version: "3.6"
services:
  broadlinkmanager:
    image: techblog/broadlinkmanager
    network_mode: host
    container_name: broadlinkmanager
    restart: unless-stopped
    volumes:
      - ./broadlinkmanager:/opt/broadlinkmanager/data
    environment:
      - ENABLE_GOOGLE_ANALYTICS=False
      - DISCOVERY_IP_LIST=10.0.4.103 #set this to your host's ip address; must be same subnet as your Broadlink devices

```

_Without_ setting it I had many interfaces but no devices were found (timeout issue?).

```

benjamin@benjamin-laptop:~/demos/broadlinkmanager-docker$ docker-compose up
Starting broadlinkmanager ... done
Attaching to broadlinkmanager
broadlinkmanager    | 2022-06-01 00:14:45.480 | DEBUG    | __main__:get_env_ip_list:69 - Environement discovered IP List []
broadlinkmanager    | 2022-06-01 00:14:45.487 | DEBUG    | __main__:get_local_ip_list:62 - Locally discovered IP List ['10.0.4.103', '172.17.0.1', '172.24.0.1', '172.22.0.1', '172.26.0.1', '172.28.0.1', '172.31.0.1', '172.18.0.1', '192.168.0.1', '172.21.0.1', '172.23.0.1', '172.29.0.1', '172.20.0.1', '172.30.0.1', '172.19.0.1', '172.27.0.1', '172.25.0.1']
broadlinkmanager    | 2022-06-01 00:14:45.487 | INFO     | __main__:<module>:124 - Broadlink will try to discover devices on the following IP interfaces: ['10.0.4.103', '172.17.0.1', '172.24.0.1', '172.22.0.1', '172.26.0.1', '172.28.0.1', '172.31.0.1', '172.18.0.1', '192.168.0.1', '172.21.0.1', '172.23.0.1', '172.29.0.1', '172.20.0.1', '172.30.0.1', '172.19.0.1', '172.27.0.1', '172.25.0.1']
broadlinkmanager    | 2022-06-01 00:14:45.489 | INFO     | __main__:<module>:133 - Configuring app
broadlinkmanager    | 2022-06-01 00:14:45.507 | INFO     | __main__:<module>:634 - Broadllink Manager is up and running
broadlinkmanager    | INFO:     Started server process [1]
broadlinkmanager    | INFO:     Waiting for application startup.
broadlinkmanager    | INFO:     Application startup complete.
broadlinkmanager    | INFO:     Uvicorn running on http://0.0.0.0:7020 (Press CTRL+C to quit)
```

After setting it, Broadlinkmanager only looks on this one interface:
```
benjamin@benjamin-laptop:~/demos/broadlinkmanager-docker$ docker-compose up
Recreating broadlinkmanager ... done
Attaching to broadlinkmanager
broadlinkmanager    | 2022-06-01 00:15:12.268 | DEBUG    | __main__:get_env_ip_list:69 - Environement discovered IP List ['10.0.4.103']
broadlinkmanager    | 2022-06-01 00:15:12.268 | INFO     | __main__:<module>:124 - Broadlink will try to discover devices on the following IP interfaces: ['10.0.4.103']
broadlinkmanager    | 2022-06-01 00:15:12.270 | INFO     | __main__:<module>:133 - Configuring app
broadlinkmanager    | 2022-06-01 00:15:12.289 | INFO     | __main__:<module>:634 - Broadllink Manager is up and running
broadlinkmanager    | INFO:     Started server process [1]
broadlinkmanager    | INFO:     Waiting for application startup.
broadlinkmanager    | INFO:     Application startup complete.
broadlinkmanager    | INFO:     Uvicorn running on http://0.0.0.0:7020 (Press CTRL+C to quit)

```
