### ISSUE TITLE
No devices at all, with Docker

### ISSUE THREAD

**Issue by KC-inDomus** [t0mer/broadlinkmanager-docker#85]
Got 3 different RM3 on my network, working fine.
Broadlinkmanage, which worked like a charm for a lot of times, stopped working sice more the one Docker version.

My configuration is correct:

```
  broadlinkmanager:
    image: techblog/broadlinkmanager
    container_name: broadlinkmanager
    network_mode: host
    volumes:
      - ~/broadlinkmanager:/opt/broadlinkmanager/data
    restart: unless-stopped
```

No idea why it doens't work.
KC
